# LTXV LoRA高级配置 (UI生成)

model:
  model_source: LTXV_13B_097_DEV
  training_mode: lora
  load_checkpoint: null
lora:
  rank: 8 # LoRA秩
  alpha: 8 # LoRA alpha
  dropout: 0 # LoRA dropout
  target_modules:
  - to_k # 目标模块
  - to_q
  - to_v
  - to_out.0
optimization:
  learning_rate: 0.0002 # 学习率
  steps: 3000 # 训练步数
  batch_size: 1 # 批处理大小
  gradient_accumulation_steps: 1 # 梯度累积步数
  max_grad_norm: 1 # 梯度范数
  optimizer_type: adamw8bit # 优化器类型
  scheduler_type: linear # 学习率调度器类型
  scheduler_params: {} # 学习率调度器参数
  enable_gradient_checkpointing: true
  first_frame_conditioning_p: 0.5
acceleration:
  mixed_precision_mode: bf16 # 混合精度模式
  quantization: int8-quanto # 量化模式
  load_text_encoder_in_8bit: true # 是否在8位下加载文本编码器
  compile_with_inductor: false # 是否使用Inductor编译
  compilation_mode: reduce-overhead # 编译模式
data:
  preprocessed_data_root: APT_scenes
  num_dataloader_workers: 1 # 数据加载器工作者数量
validation:
  prompts:
  - APT a female character with blonde hair and a blue and white outfit holding a
    sword
  - APT a female character with blonde hair in a fighting stance with a serious expression
  - APT a female character wearing a white and blue outfit with gold accents in a
    room
  negative_prompt: worst quality, inconsistent motion, blurry, jittery, distorted
  video_dims:
  - 416 # 4090推荐分辨率
  - 704 # 4090推荐分辨率
  - 97 # 4090推荐帧数
  seed: 996
  inference_steps: 25 # 生成视频的步数
  interval: null # 生成视频的间隔步数
  videos_per_prompt: 1
  guidance_scale: 3.5
checkpoints:
  interval: 300 # 保存检查点的间隔步数
  keep_last_n: -1
flow_matching:
  timestep_sampling_mode: shifted_logit_normal # 时间步采样模式
  timestep_sampling_params: {}
seed: 42
output_dir: outputs/APT_lora_r64_int8-quanto
