model:
  model_source: LTXV_13B_097_DEV
  training_mode: lora
  load_checkpoint: null
lora:
  rank: 64
  alpha: 64
  dropout: 0
  target_modules:
  - to_k
  - to_q
  - to_v
  - to_out.0
optimization:
  learning_rate: 0.0002
  steps: 200
  batch_size: 1
  gradient_accumulation_steps: 1
  max_grad_norm: 1
  optimizer_type: adamw8bit
  scheduler_type: linear
  scheduler_params: {}
  enable_gradient_checkpointing: true
  first_frame_conditioning_p: 0.5
acceleration:
  mixed_precision_mode: bf16
  quantization: int8-quanto
  load_text_encoder_in_8bit: true
  compile_with_inductor: false
  compilation_mode: reduce-overhead
data:
  preprocessed_data_root: C:\LTX-Video-Trainer\train_date\TEST\.precomputed
  num_dataloader_workers: 4
validation:
  prompts:
  - TEST a female character with blonde hair and a blue and white outfit holding a sword
  - TEST a female character with blonde hair in a fighting stance with a serious expression
  - TEST a female character wearing a white and blue outfit with gold accents in a room
  negative_prompt: worst quality, inconsistent motion, blurry, jittery, distorted
  video_dims:
  - 320
  - 320
  - 25
  seed: 42
  inference_steps: 50
  interval: null
  videos_per_prompt: 1
  guidance_scale: 3.5
checkpoints:
  interval: 250
  keep_last_n: -1
flow_matching:
  timestep_sampling_mode: shifted_logit_normal
  timestep_sampling_params: {}
seed: 42
output_dir: outputs/TEST_lora_r64_int8-quanto
